# Generated by Django 5.1 on 2024-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="채팅방 이름")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en-US", "English"),
                            ("ko-KR", "Korean"),
                            ("ja-JP", "Japanese"),
                            ("zh-CN", "Chinese"),
                            ("es-ES", "Spanish"),
                            ("fr-FR", "French"),
                            ("de-DE", "German"),
                            ("it-IT", "Italian"),
                            ("pt-PT", "Portuguese"),
                            ("ru-RU", "Russian"),
                            ("th-TH", "Thai"),
                        ],
                        default="en-US",
                        max_length=10,
                        verbose_name="언어",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")],
                        default=1,
                        verbose_name="레벨",
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        help_text="Frompt에 직접 사용됨. 한글인 경우 영어로 번역되어 저장",
                        max_length=100,
                        verbose_name="상황 영문",
                    ),
                ),
                (
                    "my_role",
                    models.CharField(
                        help_text="Frompt에 직접 사용됨. 한글인 경우 영어로 번역되어 저장",
                        max_length=100,
                        verbose_name="나의 역할 영문",
                    ),
                ),
                (
                    "gpt_role",
                    models.CharField(
                        help_text="Frompt에 직접 사용됨. 한글인 경우 영어로 번역되어 저장",
                        max_length=100,
                        verbose_name="GPT 역할 영문",
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
    ]
