# Generated by Django 5.1 on 2024-09-20 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="채팅방 이름",
            ),
            preserve_default=False,
        ),
    ]
